# Generated by Django 4.1.7 on 2023-04-11 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0002_alter_profile_pix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='pix',
            field=models.ImageField(blank=True, default='profile.jpg', null=True, upload_to='Profile'),
        ),
    ]
