# Generated by Django 4.1.7 on 2023-04-11 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0005_remove_profile_firstname_remove_profile_lastname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='dob',
            field=models.CharField(max_length=150),
        ),
    ]
